export const hikima = [
    {id:"1", text: "Ka gaggauta alkhairi domin komai lokaci gareshi"},
    {id:"2", text: "Ubangiji idan ya baka to babu mai kwace maka, idan ya hanaka babu mai baka, ka nema a wurinsa"},
    {id:"3", text: "Idan har kayi mani abinda ya bata min rai, hakan ya nuna cewar bansan halinka ba kenan, domin idan nasan halinka na gama da kai"},
    {id:"4", text: "Duk wanda yake kaunarka ai baya gulmarka sai dai yabonka"},
    {id:"5", text: "Idan har kanada dalilin yarda dani, to baka yarda dani ba, shi dalili chanzawa yake"},
    {id:"6", text: "A ganina ilimi yafi haske haske, shi kuma jahilci yafi duhu duhu"},
    {id:"7", text: "A dalilin soyayyah ko kiyayyah, komai akayi daidai ne, domin masoyinka ya wuce komai, haka makiyinka ya wuce komai"},
    {id: "8", text: "Idan Allah ya hanaka wani abu, to babu wanda zai baka, kayi dogaro da allah shi kadai"},
    {id: "9", text: "Damuwa bata kawar da matsalar da kake ciki"},
    {id: "10", text: "Allah yana tare da kai"},
    {id: "11", text: "Damuwa da abinda ya wuce shine cikakken hauka."},
    {id: "12", text: "Kada ka manta abinda wani yace maka a yayin da yake cikin bacin rai."},
    {id: "13", text: "Kowa daga nesa yafi kyau, zo mu zauna zo mu saba."},
    {id: "14", text: "Al'amarin mumini yana da ban sha'awa, idan alkhairi yasameshi sai ya gode, idan sharri yasameshi sai yayi hakuri, duka alkhairi ne gareshi."},
    {id: "15", text: "Baka gane masoyinka na gaskiya sai wata musiba ta sameka."},
    {id: "16", text: "Idan har dagaske kanaso ka gagara to kasanya Alqur'ani ya zamto abokin hirarka."},
    {id: "17", text: "Ba'a arziki da kayan wani, wahala ce kawai zaka sha."},
    {id: "18", text: "Kada ka yawaita surutu, ya kashe zuciya kuma yana rage mutumci."},
    {id: "19", text: "Koda wasa kada ka taba yarda aci mutuncinka."},
    {id: "20", text: "Duk arzikin macce idan bata da miji to miskiniya ce."},
    {id: "21", text: "Ka nemi yardar Allah kawai, domin yarda mutane gaba daya ba zata taba samuwa ba."},
    {id: "22", text: "Idan kaji wani yana zaginka, kada ka damu, domin wani na can yana yabon ka, haka duniya take."},
    {id: "23", text: "Kada gurin duniya ya hanaka tuna cewar wata rana zaka barta."},
    {id: "24", text: "Wasu suna da tarin dukiya, wasu kuma basu da ita, haka Allah ya tsara, kowa ya rike matsayinsa, yayi rayuwa dai-dai dashi."},
    {id: "25", text: "Idan damuwarka babba ce to ka barma Allah ita, idan damuwarka karama ce to ka barma Allah ita."},
    {id: "26", text: "Kowane kare gurinsa ya zamto zaki, amma sai dai akwai bambamci tsakanin haushi da kuma gurnani."}
]